### PR TITLE
Chef requires Ruby 2.2.2+ now

### PR DESCRIPTION
**Pull request by tas50**
As of 12.14 we require Ruby 2.2.2

Signed-off-by: Tim Smith tsmith@chef.io

### CODE REVIEW

**Comment by davidwrede** [comment]
@tas50, if people are running older versions of the client, will this version of Ruby break them? I'm wondering if we need to add a note to that bullet point.

**Comment by tas50** [comment]
@davidwrede  We required 2.1 before so this had been wrong for a LONG time

**Comment by tas50** [comment]
Also if they use 2.2+ they can still install say 12.12 or 12.13.

**Comment by davidwrede** [comment]
Understood, @tas50. Thanks for the clarification.

**Pull request closed without merging**
