### PR TITLE
Update quick_start.rst

### PR DESCRIPTION
**Pull request by discentem**
fixed ``cookbooks/recipes/default.rb`` to be ``cookbooks/first_cookbook/recipes/default.rb``

### CODE REVIEW

**Comment by brewn** [comment]
tenor-68757815

**Comment by discentem** [comment]
Thanks Nick! @brewn

**Comment by discentem** [comment]
hmm... the docs don't get automatically updated?

**Comment by brewn** [comment]
@discentem Nope - the change will go live soon, though.

**Pull request merged**
