### PR TITLE
Fix infra language page headings

### LINKED ISSUE #2990: Fix headings in infra language pages
## Description
Several of the Infra Language pages don't have H2 headings. The TOC script looks for H2's and won't add a TOC if it doesn't find any so those pages are missing a TOC as a result.

### PR DESCRIPTION
**Pull request by IanMadd**
Signed-off-by: IanMadd <imaddaus@chef.io>

### Description

Fix headings in Infra Language pages.

### Issues Resolved

#2990

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by tas50** [comment]
While technically correct these headers are WAY too big now. I had them all and H2 originally and dropped them down to H3 for readability on the page

**Comment by tas50** [comment]
This is rendering oddly

image

**Comment by IanMadd** [comment]
We can change the css of the H2 headings, but we've got to make them H2 for accessibility reasons.

**Comment by IanMadd** [comment]
With pages like https://deploy-preview-2996--chef-web-docs.netlify.app/infra_language/checking_architectures/, it might make sense to change those headings to a definition list.

**Review by kagarmoe — APPROVED** [review]

**Pull request merged**
