### PR TITLE
Lint markdown

### LINKED ISSUE #2919: Improve and enforce Markdownlint in CWD

### PR DESCRIPTION
**Pull request by damacus**
## Description

Lint markdown

## Issues Resolved

- Resolves #2919

## Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by damacus** [comment]
This one is going to be tricky to implement given how many HTML tables we have.

**Comment by IanMadd** [comment]
I'm wondering if there's a way to get this to run only on the pages/sections that are changed in a PR. We've got ~25000 MD Lint errors and they're not going to get fixed any time soon, so this is going to fail for every PR. Also tables.

**Comment by kagarmoe** [comment]
We're working on this in https://github.com/chef/chef-web-docs/pull/3045

**Comment by kagarmoe** [comment]
@IanMadd https://pre-commit.com/ looks interesting

**Comment by kagarmoe** [comment]
Ok, I have #3045 where I think it needs to be.

**Comment by damacus** [comment]
@kagarmoe would you like me to setup pre-commit for this repo?

**Comment by damacus** [comment]
Superseded by #3045

**Pull request closed without merging**
