### PR TITLE
Replace Chef Client / chef-client with Chef Infra Client

### PR DESCRIPTION
**Pull request by tas50**
Mostly updates to the resource text to match the latest marketing wording.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by kagarmoe** [comment]
The release notes should not change. We need to reset and remove these files from the PR.

**Comment by kagarmoe** [comment]
The release notes should not change. We need to reset and remove these files from the PR.

**Comment by kagarmoe** [comment]
@mjingle This is a gigantic PR. It fixes a/the articles, making "The Chef Infra Client" to "Chef Infra Client", etc. Except where our brand name modified a noun and such. It also makes most uses of Chef Infra Client run take *a* definite article.

**Review by mjingle — APPROVED** [review]
tenor-104246691

**Pull request merged**
