### PR TITLE
Updated command to include sudo prefix

### PR DESCRIPTION
**Pull request by kelsotodd**
There was one command missing the sudo prefix

### Description

Corrects the command for users following the instructions.

### Definition of Done

N/A 

### Issues Resolved

None

### Check List

- [X] Spell Check
- [X] Local build
- [X] Examine the local build
- [X] All tests pass

### CODE REVIEW

**Review by tas50 — APPROVED** [review]

**Review by mjingle — APPROVED** [review]

**Comment by mjingle** [comment]
@kelsotodd Hi! Can you add your DCO signoff to the PR? Thanks!

**Comment by kagarmoe** [comment]
Declaring this an obvious fix.

**Comment by kelsotodd** [comment]
> 
> 
> @kelsotodd Hi! Can you add your DCO signoff to the PR? Thanks!

Hi @mjingle 

Am I able to add DCO signoff post merge? 

Thanks

**Comment by mjingle** [comment]
@kelsotodd Hi! This PR is considered an obvious fix and therefore does not need a DCO signoff. 

If you would like, we can revert the changes so you can add a DCO to this PR. Please let us know what you decide!

**Comment by kelsotodd** [comment]
> 
> 
> @kelsotodd Hi! This PR is considered an obvious fix and therefore does not need a DCO signoff.
> 
> If you would like, we can revert the changes so you can add a DCO to this PR. Please let us know what you decide!

Happy to leave it as-is, thank you!

**Pull request merged**
