### PR TITLE
Massive copyediting for true, false, and Default Values

### PR DESCRIPTION
**Pull request by mjingle**
Signed-off-by: Mary Jinglewski <mjinglewski@chef.io>

### Description

Cleans up "True, False" values to "true, false" and fixes formatting for various **Default Value:**

### Definition of Done

When the dtags are resolved.

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Review by tas50 — APPROVED** [review]

**Comment by tas50** [comment]
Thanks for fixing them all

**Comment by mjingle** [comment]
Funnily enough, I think I'm 2/3rd of the way through by my estimations. I did find some 'nil' default values, which I kept in the paragraph form. Didn't you want those gone, @tas50? I can keep chipping away at this.

**Comment by tas50** [comment]
We should probably remove nil defaults. They don't really mean much to users

**Comment by mjingle** [comment]
I'll put the nils in another PR. Hopefully that will make reviewing less painful.

**Pull request merged**
