### PR TITLE
Updated documents for MSYS-752 changes.

### PR DESCRIPTION
**Pull request by Vasu1105**
Updated docs based on changes made in [#6815](https://github.com/chef/chef/pull/6815)

Signed-off-by: Vasu1105 <vasundhara.jagdale@msystechnologies.com>

### CODE REVIEW

**Comment by Vasu1105** [comment]
Merge after [#6815](https://github.com/chef/chef/pull/6815) gets released.

**Comment by tas50** [comment]
We need to update this to reflect that the individual properties are now in 14.1, not the whole resource. We still support Chef 13 so users need to understand what works in 13.X and what works in 14.1.

**Comment by brewn** [comment]
Yeah, I'll fix the versioning stuff before this goes out.

**Comment by Vasu1105** [comment]
@tas50 All of the properties are same. I am checking where I specifically mention about version 14.1. I have added more elaborate description about the properties so that user can use it wisely.

**Comment by btm** [comment]
Chef 14.1 was released today. https://discourse.chef.io/t/chef-client-14-1-released/13032

**Comment by tas50** [comment]
@brewn We should be good to merge this now

**Pull request merged**
