### PR TITLE
[MSYS-708]Update doc for chef-provisioning-aws

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Update doc for chef-provisioning-aws

### CODE REVIEW

**Comment by brewn** [comment]
@dheerajd-msys does this need to wait on a release?

**Comment by dheerajd-msys** [comment]
Changes are related to AWS SDK V2 in `chef-provisioning-aws v3`

**Comment by btm** [comment]
@brewn [chef-provisioning-aws](https://rubygems.org/gems/chef-provisioning-aws) v3 was released on 11/20. ChefDK 2.4.15 is expected to release today, which contains v3. Either way, we can ship this soon.

**Comment by brewn** [comment]
Thanks @btm I'll get this ready to go out today.

**Pull request merged**
