### PR TITLE
Add dnf pre-deprecation

### PR DESCRIPTION
**Pull request by lamont-granquist**
waiting on chef/chef#4894

### CODE REVIEW

**Comment by tas50** [comment]
Need to go in index.rst to get the build green. Also needs to be wired up on the deprecations page.

**Comment by davidwrede** [comment]
@lamont-granquist Add this topic to the toctree in the index file as well as partially filled out new entry in deprecation table. Add/Edit as you see fit.

**Comment by lamont-granquist** [comment]
still on hold until chef/chef#4894 gets merged, thanks for the commits tho..

**Comment by thommay** [comment]
This has been merged upstream so we should update the docs.

**Comment by davidwrede** [comment]
@thommay Yup. Looks like 12.18.31 is moving to stable today, so we'll get this change merged in. Thanks for the heads up.

**Comment by davidwrede** [comment]
gif-keyboard-14588890288886948753

**Pull request merged**
