### PR TITLE
Tell swiftype what we want indexed

### PR DESCRIPTION
**Pull request by IanMadd**
Signed-off-by: IanMadd <imaddaus@chef.io>

### Description

Tell Swiftype the section of each page that we want indexed. This excludes things like the left nav and the TOC.

https://swiftype.com/documentation/site-search/crawler-configuration/content-inclusion-exclusion

This also removes the main docs site landing page and the site map from the index.

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by kagarmoe** [comment]
Should we add a 'false' on the side nav, or does it only index 'true' and exclude everything else?

**Comment by IanMadd** [comment]
According to the docs, any tag outside of a tag with `data-swiftype-index='true'` will be ignored unless it's specifically added using that same tag. 

https://swiftype.com/documentation/site-search/crawler-configuration/content-inclusion-exclusion#content_inclusion

The alternative is to `data-swiftype-index='false'` to exclude specific sections.
https://swiftype.com/documentation/site-search/crawler-configuration/content-inclusion-exclusion#content_exclusion

**Comment by kagarmoe** [comment]
This doesn't entirely make sense to me; I would think that the default behavior would be either to index or not to index. I'm assuming that the default is to index everything, so let's try excluding the parts we don't want indexed (header, navs, footer) and see if it works as expected.

**Comment by IanMadd** [comment]
I don't understand what's not making sense. The default is to index everything unless you tell it what you want index, then it just indexes those parts. Per the example, the only content that gets indexed is what is inside the div with `data-swiftype-index='true'` :

```

<body>

  This is content that will not be indexed by the Swiftype crawler.

  <div data-swiftype-index='true'>
    <p>
      All content under the above div tag will be indexed.
    </p>
    <p>
      Content in this paragraph tag will be included from the search index!
    </p>
  </div>

  This content will not be indexed, since it isn't surrounded by an include tag.

</body> 
```

**Review by kagarmoe — APPROVED** [review]
I am genuinely excited to see how this works!

tenor-232050667

**Pull request merged**
