### PR TITLE
update chef desktop documentation

### PR DESCRIPTION
**Pull request by rishichawda**
Signed-off-by: rishichawda <chawda.rishii@gmail.com>

## Description
Minor refactor of the Chef Desktop documentation's menu based on the changes in the content. The PR for content is [here](https://github.com/chef/desktop-config/pull/366) on the chef/desktop-config repo.

## Definition of Done
Documentation is reviewed and approved by the team.

## Issues Resolved
https://github.com/chef/desktop-config/issues/335

## Related PRs
https://github.com/chef/desktop-config/pull/366

## Check List

- [x] Spell Check
- [x] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by kagarmoe** [comment]
Hi! Most of the configuration that you're proposing happens through the front-matter on the documentation files.

**Comment by rishichawda** [comment]
Yep, I just added the new menu items based on the structure. Most of the changes are in desktop repo.

**Comment by rishichawda** [comment]
@kagarmoe I'll be updating this PR once https://github.com/chef/desktop-config/pull/419 is merged to master. The desktop documentation that is deployed right now is probably broken because the _vendor directory contains old updates.

**Comment by kagarmoe** [comment]
Closed in favor of https://github.com/chef/chef-web-docs/pull/3340

**Pull request closed without merging**
