### PR TITLE
Add note about source of resource docs

### PR DESCRIPTION
**Pull request by IanMadd**
Signed-off-by: IanMadd <imaddaus@chef.io>

### Description

Adds an accordion "Edit this page" to resource pages. The user clicks on it and instructions drop down telling them how to make a PR to make a correction to the resource docs.

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by IanMadd** [comment]
Check the top where it says "Edit this page." 
https://deploy-preview-2495--chef-web-docs.netlify.app/resources/apt_package/

**Comment by kagarmoe** [comment]
I like the drop-down action, we could use that in a lot of different places.
What would you think of changing the wording to "Edit this page in the Chef repository" & then the drop-down gives the link?

**Comment by IanMadd** [comment]
I think we need some kind of explanation that this is a generated file. But maybe something shorter.

This page is generated from the <a href="https://github.com/chef/chef">Chef repository</a>.
To suggest a change, submit a pull request against this page: 
<a href="https://github.com/chef/chef/blob/master/lib/chef/resource/some_resource.rb">https://github.com/chef/chef/blob/master/lib/chef/resource/some_resource.rb</a></br>

**Comment by kagarmoe** [comment]
Edit this page in the Chef repository
[dropdown]
This page is generated from the Chef source code.
To suggest a change, submit a pull request at:
https://github.com/chef/chef/blob/master/lib/chef/resource/some_resource.rb

**Comment by IanMadd** [comment]
The problem with this is that they're not submitting a pull request at that file, they submit the pull request to the chef/chef repo.  

Edit this page in the Chef repository
[dropdown]
This page is generated from the Chef source code.
To suggest a change, edit the [some_resource.rb](https://github.com/chef/chef/blob/master/lib/chef/resource/some_resource.rb) file and submit a pull request to the [Chef repository](https://github.com/chef/chef/).

**Review by kagarmoe — APPROVED** [review]
tenor-150712217

**Pull request merged**
