### PR TITLE
Fix failures in make docker-preview

### PR DESCRIPTION
**Pull request by tas50**
Modernize things to match our container

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Review by kagarmoe — APPROVED** [review]

**Review by mjingle — CHANGES_REQUESTED** [review]
So when this change is run locally, I get an error message. Going to continue working on this, but for now, this PR should not be merged.

**Comment by tas50** [comment]
@mjingle you might want to prune out all your old docker containers first: docker system prune --all

**Comment by mjingle** [comment]
@tas50 It's amazing what a bit of cleaning does. 😅 Thank you! PR fine and ready to go. 👍

**Review by mjingle — APPROVED** [review]
tenor-182245185

**Pull request merged**
