### PR TITLE
Update log resource docs for count_log_resource_updates chef config option

### PR DESCRIPTION
**Pull request by NimishaS**
Relates to https://github.com/chef/chef/pull/5267

### CODE REVIEW

**Comment by btm** [comment]
Pending acceptance of https://github.com/chef/chef/pull/5267

**Comment by NimishaS** [comment]
Ready for review

**Comment by mwrock** [comment]
👍

**Comment by rhass** [comment]
:+1:

**Comment by davidwrede** [comment]
This commit was merged in with another PR and the change is live.

**Pull request closed without merging**
