### PR TITLE
add new commands to supermarket-ctl

### PR DESCRIPTION
**Pull request by robbkidd**
Quality metrics got some commands added to the suite.

### CODE REVIEW

**Review by iennae — APPROVED** [review]
LGTM

**Review by davidwrede — APPROVED** [review]
Looks great, @robbkidd!

**Comment by robbkidd** [comment]
Of course it's after you merge that I notice at least one grammar error I dutifully copy'n'pasted over and over. Another PR incoming!

**Comment by robbkidd** [comment]
Over in #622

**Pull request merged**
