### PR TITLE
Moved count_log_resource_updates info above Syntax as a Note

### PR DESCRIPTION
**Pull request by NimishaS**

### CODE REVIEW

**Comment by btm** [comment]
This makes more sense to me, thanks, @davidwrede ?

**Comment by davidwrede** [comment]
I'm fine with the change and will get it merged today.

Thanks for the update, @NimishaS!

**Comment by davidwrede** [comment]
Commit has been merged. Will be live in a couple hours.

**Comment by davidwrede** [comment]
Change is live.

**Pull request closed without merging**
