### PR TITLE
Update configuration documentation

### PR DESCRIPTION
**Pull request by Systemmanic**
add section about using ssh-agent

### Description

Updating documentation to include the `ssh_agent_signing` option.

I spent a while trying to get `ssh-agent` working with `knife` and it wasn't until I looked into the source I seen this was available. It's in the change log but not the docs:

https://github.com/chef/chef/blob/5c8d3a5deae5f764c6b26d99261a4d8696ec01ab/RELEASE_NOTES.md#ssh-agent-support-for-user-keys

### Definition of Done

None

### Issues Resolved

None.

### Check List

- [x] Spell Check
- [x] Local build
- [x] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Review by kagarmoe — APPROVED** [review]

**Comment by tas50** [comment]
@kagarmoe we should not that this is a 14.2+ feature

**Comment by Systemmanic** [comment]
Also note I'm opening an issue now about this feature in `chef/chef` as it's not currently working.

**Comment by mjingle** [comment]
Okay, we'll update the PR with the note about this being a 14.2+ feature, but we'll hold off on merging until we know the outcome of if this feature is working or not.

**Comment by Systemmanic** [comment]
Issue https://github.com/chef/chef/issues/7635 opened.

**Comment by Systemmanic** [comment]
Issue https://github.com/chef/chef/issues/7635 has been resolved.

It requires the key in a specific format. I've update the docs to reflect this requirement.

**Comment by Systemmanic** [comment]
This should all be good now as the issue that was opened about the feature being broken was incorrect.

This document change would prevent my misconfiguration from happening again, or to someone else! 😄

**Comment by mjingle** [comment]
@dkanejs Thank you so much for your submission and persistence on this PR! Because this is a PR from a remote fork, our set-up means that we had to include your work to chef-web-docs through other means. Please see https://github.com/chef/chef-web-docs/pull/1764

**Pull request closed without merging**
