### PR TITLE
Update Chef Backend upgrade instructions for 2.x

### PR DESCRIPTION
**Pull request by stevendanna**
Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

**Comment by stevendanna** [comment]
This refers to code that is not yet released.  Please don't merge until we are ready to release Chef Backend.

**Comment by brewn** [comment]
Thanks @stevendanna!

**Comment by stevendanna** [comment]
@brewn We are close to release and we want to make sure the install instructions are in place when we send the release notes.  Would you mind taking a look at this and deploying it when you get a chance?

**Comment by brewn** [comment]
@stevendanna sure, I'll get this ready and merge it

**Pull request merged**
