### PR TITLE
Kg/update link

### PR DESCRIPTION
**Pull request by kagarmoe**
Updates a link to Automate docs that pointed to the old Automate 1 docs.

### CODE REVIEW

**Comment by phiggins** [comment]
This has a lot of unrelated seeming changes and merge conflicts with master, does this need to be rebased?

**Comment by kagarmoe** [comment]
Rebasing doesn't seem to help. I've hit something odd in VSCode.

**Comment by phiggins** [comment]
This PR seems to have been branched off of #2367, which has not been merged yet and appears itself to be quite out of date. I rebased onto master without those commits.

**Review by phiggins — APPROVED** [review]

**Comment by kagarmoe** [comment]
Thank you for your help @phiggins! Isn't this strange? My workflow is **always** to return to master before starting a new branch. (Thanks to @colincam!)This is the second PR with changes from unmodified branches that merely _exist_ in my larger environment.

**Review by mjingle — APPROVED** [review]

**Pull request merged**
