### PR TITLE
Add EOL dates for Chef 13, Provisioning, and DK 2

### PR DESCRIPTION
**Pull request by tas50**
We know these will all EOL on April 30, 2019.

### CODE REVIEW

**Comment by krasnow** [comment]
@tas50 - We will officially announce EOL for Provisioning on Feb 15th, so the EOL date should be +6 months out on that. I'll update it to say August 31, 2019. Otherwise LGTM.

**Comment by krasnow** [comment]
Oh and then I noticed that the dates weren't in the right columns. And we hadn't market Compliance as EOL even though the date had passed. So I fixed all that too.

**Comment by tas50** [comment]
Thanks @krasnow. Anything else we should do here @mjingle @kagarmoe

**Review by mjingle — APPROVED** [review]
tenor-173947447

**Pull request merged**
