### PR TITLE
links to central community coc page

### PR DESCRIPTION
**Pull request by nellshamrell**
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

### Description

This page previously had an out of date version of our community standards and Code of Conduct. Rather than trying to maintain the same content in multiple places (which can easily get out of sync), this links to Chef's main Code of Conduct page. The content is nearly identical to what was previously on this page, but it has the updated community advocate names.

### Definition of Done

Merged and deployed to the docs site

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [x] Spell Check
- [x] Local build
- [x] Examine the local build
- [x] All tests pass

### CODE REVIEW

**Comment by kagarmoe** [comment]
Hi Nell,
Thanks for the PR! I appreciate your desire to single-source the COC, it is a good idea. I have a couple of thoughts. First, we in docs feel fairly strongly that this is essential information, and as such also needs to be published in our official documentation--the content that is copyrighted and will be discoverable in search. Second, insisting that all users travel out to GitHub as the only source of information about the COC introduces a fairly high barrier for novice users who either aren't yet comfortable with GitHub, as well as for anyone who is interested only in scanning the docs for high-level information. We would also like to support these users who, for whatever reason, aren't interested in moving out to GitHub.

These are my suggestions:
1. As a temporary step, let's copy the COC into the documentation.
2. Let's examine how we can automate pulling (or pushing) the COC content into documentation when we migrate the docs to Hugo. There are some available patterns, such as outputting the COC to a .toml file, which docs then consumes with every build.

What do you think?

**Review by kagarmoe — CHANGES_REQUESTED** [review]
Discussion in the comment. Thanks!

**Comment by nellshamrell** [comment]
Hello all! I just conferred with @kagarmoe in person and she asked me to copy and paste the CoC from the GitHub repo (which is in GitHub markdown) into the rst document. She told me that the docs team would take care of modifying it from GitHub markdown to rst.

**Review by IanMadd — APPROVED** [review]
Looks good! Thanks @nellshamrell !
tenor-201699813

**Review by kagarmoe — APPROVED** [review]
tenor-23506877

**Pull request merged**
