### PR TITLE
List formatting

### PR DESCRIPTION
**Pull request by kagarmoe**
Signed-off-by: kagarmoe <kgarmoe@chef.io>

Ideas for better lists.

### CODE REVIEW

**Comment by IanMadd** [comment]
This one's a bit weird. This set of list items are bolded: 
https://deploy-preview-2720--chef-web-docs.netlify.app/automate/install/#backup-externally-deployed-elasticsearch-to-aws-s3

and these aren't because Hugo didn't put `<p>` inside each list item (the MD looks the same though 🤷) :
https://deploy-preview-2720--chef-web-docs.netlify.app/automate/install/#backup-externally-deployed-elasticsearch-to-local-filesystem

**Comment by IanMadd** [comment]
Another thing to consider is the 1st example here, which would style the ordered list numbers: https://css-tricks.com/custom-list-number-styling/

**Comment by kagarmoe** [comment]
@IanMadd This one uses bold numbers. I'm on the fence if it helpful or distracting.

**Comment by IanMadd** [comment]
It doesn't really seem to be changing that much.

I'm comparing this: 
https://deploy-preview-2720--chef-web-docs.netlify.app/automate/datafeed/#edit-a-data-feed-instance

to this: 
https://docs.chef.io/automate/datafeed/#edit-a-data-feed-instance

My general instinct is that if the change doesn't really improve the readability, then it just becomes code that has to be maintained later so we shouldn't make the change.

**Comment by kagarmoe** [comment]
I'll return to this when I have more time.

**Pull request closed without merging**
