### PR TITLE
Fix run-on sentence

### PR DESCRIPTION
**Pull request by karlamrhein**
Added a period to fix a run-on sentence.

## Description

Fixed run-on sentence by adding a period. 

## Definition of Done

sentence is now correct. 

## Issues Resolved

None

## Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by IanMadd** [comment]
@karlamrhein can you add "Obvious fix" to your commit message. See https://github.com/chef/chef/blob/main/CONTRIBUTING.md#chef-obvious-fix-policy

**Review by karlamrhein — COMMENTED** [review]
Obvious fix.

**Comment by karlamrhein** [comment]
I will amend the commit message and add "obvious fix" to it.

**Comment by IanMadd** [comment]
Replace by #4345 for the DCO.

**Pull request closed without merging**
