### PR TITLE
Tiered installations are no longer deprecated

### PR DESCRIPTION
**Pull request by teknofire**
The link to the tiered installation instruction still has them labeled as deprecated when in fact they are no longer deprecated and are a supported configuration.

I also removed the link to the DRBD installation instructions as that is now EOL'd and should never be used.

### CODE REVIEW

**Comment by kagarmoe** [comment]
Thanks! We need to also remove All DRBD content from the repo. This could take us a few days.

**Review by btm — APPROVED** [review]

**Comment by kagarmoe** [comment]
What should we do with all of the DRBD-related content in other files? Particularly the `keepalived` content. Have we fully removed DRBD from the Chef Infra Server ctl? (see` chef_master/source/ctl_chef_server.rst`)

**Comment by kagarmoe** [comment]
Do not merge! Need to check the build and address:

- [x] `ctl_shef_server.rst`
- [ ] `install_server_ha_aws.rst`
- [ ] `server_data.rst`
- [ ] `server_firewalls_and_ports.rst`
- [ ] `server_monitor.rst`

**Comment by markan** [comment]
@kagarmoe added this PR to remove keepalived support https://github.com/chef/chef-server/pull/1664

**Comment by kagarmoe** [comment]
@markan Could you take at look at these four files? I'd like an expert's eye on what to remove.

- [ ] `install_server_ha_aws.rst`
- [ ] `server_data.rst`
- [ ] `server_firewalls_and_ports.rst`
- [ ] `server_monitor.rst`

**Review by markan — APPROVED** [review]
This generally looks good. I added / pushed some further cleanups; a number of files can go away and others had a little bit of remaining cruft.

**Review by kagarmoe — APPROVED** [review]

**Comment by kagarmoe** [comment]
tenor-247662914

**Pull request merged**
