### PR TITLE
Retire AIX 6.1 and EL5 (OEL, RHEL, CentOS 5) support

### PR DESCRIPTION
**Pull request by juliandunn**
Merge this on December 31, 2017 per the platform support policy.

### CODE REVIEW

**Comment by brewn** [comment]
Thanks @juliandunn - I've added this to my calendar for the 31st and I'll fix the dtags issues and merge it then.

**Comment by juliandunn** [comment]
@brewn did you merge this separately? I can close it now?

**Comment by kagarmoe** [comment]
It is not yet merged. Will fix the dtags and merge.

**Comment by kagarmoe** [comment]
tenor-49732883

**Pull request merged**
