### PR TITLE
Reconcile source, nav, and index

### PR DESCRIPTION
**Pull request by kagarmoe**
Signed-off-by: kagarmoe <kgarmoe@chef.io>

Getting to the odds-and-ends of our content.

UPDATE: 
* Made this work by adding files back in
* Added `resource_chef_* ` into the nav bar
* Updated the file list below
* Removed deprecations from the file list

```
##################################################
The number of docs source files:
403
##################################################
Source files that are not included in the left nav:
45
##################################################
azure_chef_cli
ctl_automate_server
delivery_server_backup
delivery_server_disaster_recovery
resource_chef_client
##################################################
Source files that are not included in the index:
58
##################################################
automate_azure
aws_opsworks_chef_automate
azure_chef_cli
chef_license_accept
config_json_delivery
config_rb_delivery
config_rb_delivery_optional_settings
ctl_automate_server
custom_resources_notes
data_collection
data_collection_ha
data_collection_without_server
delivery_users_and_roles
dsl_delivery
elasticsearch_and_kibana_auth
integrate_chef_automate_saml
manage
workstation_setup
##################################################
Source files that are in the nav but not the index:
3
##################################################
delivery_server_backup
delivery_server_disaster_recovery
resource_chef_client
##################################################
Source files that are in the index but not the nav:
16
##################################################
automate_azure
aws_opsworks_chef_automate
chef_license_accept
config_json_delivery
config_rb_delivery
config_rb_delivery_optional_settings
custom_resources_notes
data_collection
data_collection_ha
data_collection_without_server
delivery_users_and_roles
dsl_delivery
elasticsearch_and_kibana_auth
integrate_chef_automate_saml
manage
workstation_setup
```

### CODE REVIEW

**Comment by IanMadd** [comment]
I fixed the toctree on index.rst, but.... There's a problem with some links on runners.rst. They link to line 366 in ctl_automate_server.rst. So maybe we get rid of runners too?

```
You can delete a runner via ``automate-ctl`` from your Chef Automate server. Log in to your Chef Automate server and run the :ref:`delete-runner` command.

After the :ref:`delete-runner` command succeeds, the specified runner should be deleted from the UI under ``Workflow -> Runners -> Manage Runners``.
```

**Comment by kagarmoe** [comment]
I think those files are all part of the Workflow docs. I'll review the PDF by Monday.

**Comment by IanMadd** [comment]
More updates (minus deprecations_* files):

It comes down to these files, should they be in the index and left nav because currently they're not:
azure_chef_cli
config_rb_delivery_optional_settings
ctl_automate_server
custom_resources_notes
delivery_server_backup
delivery_server_disaster_recovery
resource_chef_client

**Review by IanMadd — APPROVED** [review]
tenor-171077120

**Pull request merged**
