### PR TITLE
Fix description of :create action

### PR DESCRIPTION
**Pull request by karlamrhein**
Fixed description of :create action.  It was the same as :create_if_missing.

Obvious fix (invoking the "obvious fix" rule)

### CODE REVIEW

**Comment by mjingle** [comment]
@karlamrhein Thank you for spotting this and letting us know about it! This is indeed a mis-paste from our code. (The `"` kind of gave it away, eh?) The correct description for this action can be found here: https://github.com/chef/chef/blob/master/lib/chef/resource/cron_d.rb#L170
Your PR should be updated accordingly to match the description in the code. I can do that if you would like.

**Comment by karlamrhein** [comment]
yes, the ```"``` was a clue!  

i just updated the PR to match the code.

**Comment by mjingle** [comment]
@karlamrhein Fantastic. Thank you so much for your contribution!

**Review by mjingle — APPROVED** [review]
tenor-199182392

**Pull request merged**
