### PR TITLE
Remove obsolete delivery ref in templates

### PR DESCRIPTION
**Pull request by vkarve-chef**
Signed-off-by: Vikram Karve <vikram.karve@progress.com>

## Description
Chef delivery/ workflow is now deprecated and the references to `.delivery` directory in templates need to be removed

## Definition of Done
No references to `.delivery` sub-folder in cookbook folder should appear in templates.

## Issues Resolved
https://github.com/chef/chef-workstation/issues/2540
https://github.com/chef/chef-web-docs/issues/3704

## Check List

- [x] Spell Check
- [x] Local build
- [x] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Review by tas50 — COMMENTED** [review]
Can we make sure the new compliance directory is here?

**Comment by kagarmoe** [comment]
Hi @vkarve-chef--could you give me @chef/docs-team access to your remote? Thanks!

**Comment by damacus** [comment]
@tas50 looks like `chef generate profile` isn't in current. So that should probably be done as another PR.

**Comment by vkarve-chef** [comment]
@damacus i do see `chef generate profile` work in the latest current build
```
$ chef -v
Chef Workstation version: 22.2.792
Chef InSpec version: 4.52.9
Chef CLI version: 5.6.0
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.31.1
Chef Infra Client version: 17.9.42
```

**Comment by vkarve-chef** [comment]
to clarify, @tas50 i will add the `chef generate` compliance phase documentation in separate PR. 
@chef/docs-team i have added the members to the fork.

**Review by tas50 — APPROVED** [review]

**Review by IanMadd — APPROVED** [review]

**Pull request merged**
