### PR TITLE
Improve pushy network port documentation

### PR DESCRIPTION
**Pull request by atrull**
### Description

Adding to the documentation to cover some edge-case issues. Port 10003 wasn't mentioned before.

### Definition of Done

The documentation is clear and understandable and relates to reality, which can bite in the case of non-local addressed/NATed chef servers.

### Issues Resolved

https://github.com/chef/opscode-pushy-server/issues/193

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by IanMadd** [comment]
Hi @atrull, thanks for the contribution. 
Can you add your DCO signoff to the pull request. Thanks!
https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by atrull** [comment]
DCO is added :) @IanMadd

**Comment by tas50** [comment]
Paging @markan to double check these ports

**Comment by tas50** [comment]
Thanks @atrull

**Pull request merged**
