### PR TITLE
Update documentation on recipe inclusion.

### PR DESCRIPTION
**Pull request by iennae**
Based on discussion in Community Chef slack, the include_recipe directive may be a little confusing. This is an attempt to clarify what the method is doing, and how to use it.

Signed-off-by: Jennifer Davis <iennae@gmail.com>

### CODE REVIEW

**Comment by iennae** [comment]
@coderanger if you have a spare moment to maybe look at the change in words and see if you think it would help clarify the misunderstanding that happened earlier in Slack, would appreciate it. Totally understand if you don't have time! Thanks so much.

**Review by coderanger — APPROVED** [review]
Looks like a solid improvement to me! 🚢 🇮🇹

**Comment by davidwrede** [comment]
Great improvement, @iennae! I'll help you fix your travis build errors and get this merged in.

**Comment by kagarmoe** [comment]
gif-keyboard-10636158335457904050

**Pull request merged**
