### PR TITLE
Properly document string vs in for user resource

### PR DESCRIPTION
**Pull request by mchugh19**
### Description
The user resource doc seemed to show uid and gid passed as strings, when they actually need to be int if numbers.

### Definition of Done
Merge doc showing both int and string examples (not using confusing integers as a string name)

### Issues Resolved
None

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by tas50** [comment]
@mchugh19 Can you sign this change off for the DCO? There's more information on why we require the DCO here: https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by mjingle** [comment]
@mchugh19 Hi! This PR is just waiting for your DCO before merging. Are there any questions we can answer for you to help make this happen?

**Comment by mchugh19** [comment]
commit Signed-off-by added. Thanks all!

**Review by IanMadd — APPROVED** [review]
Thanks for your contribution @mchugh19!
tenor-143089460

**Pull request merged**
