### PR TITLE
Fixing deprecated products

### PR DESCRIPTION
**Pull request by dishanktiwari2501**
### Description

Deprecating the following from the Chef Docs:

- Chef Infra Server 12
- ChefDK
- Chef Workflow
- Push Jobs

Reference Link: https://github.com/chef/chef-web-docs/issues/2807

### Definition of Done

The Task is Still In Progress (WIP)

### Issues Resolved

**Definition of Done**
- Workflow pages consolidated in Legacy section
- Push Jobs pages consolidated in Legacy section
- Workflow commands removed from docs
- Push Jobs commands removed from docs
- All discussions of Push Jobs or Workflow removed from docs
- Remove Push Jobs and Workflow from docs and left nav

- Remove all Chef Infra Server 12.x-specific notes and content
- Remove all references to ChefDK and replace with Chef Workstation

### Check List

- [x] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by tas50** [comment]
I was under the impression that our process would be to move EOL products into the legacy section for some time period.

**Comment by kagarmoe** [comment]
@tas50 Right now the process is to move the deprecated products to Legacy and remove the docs when they reach the EOL date.

**Comment by kagarmoe** [comment]
@dishanktiwari2501 The files in the `_vendor` directory are content that is pulled in from other product repositories. We can't change that content in this repository, so you need to restore the `_vendor/` files in this PR and make the changes in the Automate and Workstation repositories. You can restore the files in this PR with `git checkout origin -- _vendor/` and then add & commit the change.

You'll find a few more hits with the search terms:
`push-jobs`
`push job`
`server 12`

@tas50 What are your thoughts about removing `New in Chef Infra Server 12`? It appears mostly in commands. I don't know that it adds helpful context for commands that were introduced four years ago.

**Review by kagarmoe — APPROVED** [review]
tenor-61054261

**Review by IanMadd — APPROVED** [review]
tenor-193817498

**Pull request merged**
