### PR TITLE
Clean up the /universe api response

### PR DESCRIPTION
**Pull request by MarkGibbons**
### Description

The result body in the example was sort of a ruby hash.  It need to be JSON. Fixed the example and made it working JSON.

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by IanMadd** [comment]
Hi @MarkGibbons, thanks for the PR. Can you add your [DCO signoff](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) to the PR. Thanks!

**Comment by MarkGibbons** [comment]
Added sign off

**Comment by tas50** [comment]
@MarkGibbons sphinx seems to be mad about some indentation

**Comment by MarkGibbons** [comment]
2 spaces per level and yanked the tabs seems to have made sphinx happy.

**Comment by tas50** [comment]
Looks good. Thanks @MarkGibbons for continuing to track down all the little places these docs need updating.

**Pull request merged**
