### PR TITLE
Clarifying what to do with a new cluster

### PR DESCRIPTION
**Pull request by moutons**
Signed-off-by: Shaun Mouton <sdmouton@devops.christmas>

### Description

backend ha install directions didn't point to what should be done next, now they do

### Issues Resolved

n/a

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Comment by moutons** [comment]
changes look good on netlify

**Comment by kagarmoe** [comment]
@moutons Could you review my edits?

**Comment by moutons** [comment]
lgtm :shipit:

**Review by IanMadd — APPROVED** [review]
tenor-43091951

**Pull request merged**
