### PR TITLE
CloudKick is long gone, also wrong link

### PR DESCRIPTION
**Pull request by rmoriz**
related https://github.com/chef-cookbooks/chef_handler/issues/54

### CODE REVIEW

**Comment by tas50** [comment]
@rmoriz This same link is in another place in the site. See the Travis failure

**Comment by rmoriz** [comment]
whoops.

**Comment by rmoriz** [comment]
fixed

**Review by tas50 — APPROVED** [review]

**Comment by davidwrede** [comment]
tenor-66645022

**Pull request merged**
