### PR TITLE
Simplify custom resource warning text

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Hi @tas50 
The link https://docs.chef.io/custom_resources_notes.html is removed with this pull request.  That page has important clues for how to write 12.5 custom resources that are not documented anywhere else in chef-web-docs that I can find.  Where to put methods related to an action was pretty baffling without that doc.  I'm not even sure the note is correct but using action_class does work.

**Comment by tas50** [comment]
I'm going to get a PR cut to move some of this logic into the main doc. Having two places to look seems really confusing and I think we can clean a lot of this up

**Comment by davidwrede** [comment]
@tas50, I'll merge this PR, but as an FYI, we will be removing the version picker and all `/release/*` content from the site soon. This means we should start flattening and including content that works for all minor versions of a given product/project release (i.e. all client 12.x content should be included in the current client docs until we cut client 13, and then all of the client 12.x content gets placed on our new archive site).

**Comment by davidwrede** [comment]
gif-keyboard-4549736293514790787

**Pull request merged**
