### PR TITLE
Document new chef-server-ctl set-secret option.

### PR DESCRIPTION
**Pull request by phiggins**
Documentation for the new option added to `chef-server-ctl set-secret` in chef/chef-server#1313.

### CODE REVIEW

**Comment by blakestier** [comment]
👍 to ship after #1313

**Comment by brewn** [comment]
For reference: https://github.com/chef/chef-server/pull/1313

Thanks for the update!

**Review by srenatus — APPROVED** [review]
The additions looks good -- just a note:
The option will exist in the _next version_ of Chef-Server, so, it's only available for >= 12.15.9. This isn't scheduled too soon, as far as I can tell (anything could happen, though), do we need some "added in version xyz" indication?

**Comment by brewn** [comment]
@srenatus Yep that's a good idea - I'll add a note to this before it gets merged.

**Review by afiune — APPROVED** [review]

**Comment by afiune** [comment]
Linking the PR that will add this functionality: https://github.com/chef/chef-server/pull/1313

**Pull request merged**
