### PR TITLE
Add workstation platforms.

### PR DESCRIPTION
**Pull request by jonsmorrow**
### Check List

- [x] Spell Check
- [x] Local build
- [x] Examine the local build
- [x] All tests pass

### CODE REVIEW

**Comment by jonsmorrow** [comment]
Please don't merge without @krasnow's approval.

**Comment by krasnow** [comment]
This looks good to me. Thanks!

**Comment by mjingle** [comment]
@jonsmorrow You'll need to add a DCO to your commit, but this is otherwise great: https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/

**Review by mjingle — APPROVED** [review]
tenor-118878896

**Pull request merged**
