### PR TITLE
returns property for chocolatey_package

### PR DESCRIPTION
**Pull request by NimishaS**
w.r.t. https://github.com/chef/chef/pull/5688

### CODE REVIEW

**Comment by NimishaS** [comment]
`dtags` check is failing here. Please guide me if I need tag around the `code` block. I saw `code` block without `dtags` too, so I am a bit confused.

**Comment by btm** [comment]
this will be in the january chef client release.

**Comment by davidwrede** [comment]
@NimishaS, the error is that updates to the shared blocks of text need to be replicated to the other files that include those blocks of text. I'll submit a PR shortly to do the replication.

**Comment by davidwrede** [comment]
Had to revert the changes in the release notes as they were for the version of the chocolatey_package resource that shipped in 12.7.

**Comment by NimishaS** [comment]
@davidwrede , do I need to make any changes?

**Comment by davidwrede** [comment]
@NimishaS, nope. You're good. Just waiting for the next release and then we'll merge the updates.

**Comment by davidwrede** [comment]
gif-keyboard-5271232399969352694

**Pull request merged**
