### PR TITLE
check-mark-lint-check should pass

### PR DESCRIPTION
**Pull request by kagarmoe**
Signed-off-by: kagarmoe <kgarmoe@chef.io>

### Description

This PR tries to fix checkmark characters that fail linting.

### Definition of Done

All the lint tests succeed.

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

### CODE REVIEW

**Review by mjingle — APPROVED** [review]
tenor-103263633

**Comment by kagarmoe** [comment]
Except, the checkmarks DON'T pass linting. Can you remove your approval, please @mjingle ?

**Comment by IanMadd** [comment]
There may not be a way to add check marks that pass the lint check, so maybe we reconfigure the lint to allow check marks?

**Comment by kagarmoe** [comment]
@IanMadd My tests are failing because of an error calling concat in the javascript.html file.
Any ideas?

 https://github.com/chef/chef-web-docs/blob/d3765bcb0924f0a84477613ac416a388c7f693e3/themes/docs-new/layouts/partials/javascript.html#L7-L8

**Review by IanMadd — APPROVED** [review]
tenor-110077832

**Pull request merged**
